### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by silverweed** [silverweed/colony#1]
**To implement for 15th Dec**    
* [x] Resources (honey, royal jelly, water)  
**Prefabs**   
* [x] Queen Bee
* [x] Worker Bee
* [x] Larva
* [x] Flower
* [x] Tree
* [x] Wasp
* [x] Resource gathering (honey, pollen, nectar, water)  
**UI**  
* [x] Bottom screen UI
* [x] Resource Counter
* [x] Bee's life (may need rework)
* [x] Choose specialization "box" when larva is selected
* [x] Event popup window
* [x] Deploy eggs in cells  
**Mechanics**  
* [x] Movement
* [x] Harvest
* [x] Fight system
* [x] At least 1 Scripted event
* [x] New colony [optional]
