### ISSUE TITLE
Roadmap beta

### ISSUE THREAD

**Issue by silverweed** [silverweed/colony#2]
# 19 Jan 2016

## Improvements
- [ ] ~~bees random movement while idle~~
- [x] better age bar
- [x] more flowers
- [x] specializations
- [x] game balancing

## Addings
- [x] events
- [ ] ~~health bar~~
- [x] bushes / trees --> a map
- [ ] ~~drones~~
- [ ] ~~fog of war~~
